#!/usr/bin/env bash
git submodule update --init --recursive
set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="meta/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}" && echo "${BASEDIR}" > "${BASEDIR}/.basedir"
